---
# tasks file for install-git-client
- name: On Ubuntu/Debian
  apt:
    name: git
    state: latest
    update_cache: yes
  when: (ansible_facts['os_family'] == "Debian") or (ansible_facts['os_family'] == "Ubuntu")

- name: On CentOS/RHEL
  yum:
    name: git
    state: latest
    update_cache: yes
  when: (ansible_facts['os_family'] == "RedHat") or (ansible_facts['os_family'] == "CentOs")
