---
# tasks file for install-nginx
- name: Install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: remove default
  file:
    path: /etc/nginx/sites-defaults/default
    state: absent

- name: remove default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Add Configure
  template:
    src: /home/ubuntu/nginx/templates/static-site-config.j2
    dest: /etc/nginx/sites-available/default

- name: create a link
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: '644'
    state: link

- name: restart
  systemd:
    name: nginx
    state: restarted
    enabled: yes
